.travis.yml
v2/client.go
v2/errors.go
v2/fake/fake.go
v2/interface.go
v2/types.go
v2/validation.go

- Implement the client
- Add a fake
- Take a first pass at adding godoc for all relevant fixtures

Implement client and add fake

---

README.md
docs/README.md
v2/client.go
v2/interface.go

make things a little incrementally better

Update README and add docs

---

v2/types.go

Add missing json tags

---

docs/README.md

On most basic concepts of OSB API.

Add most basic doc

---

.travis.yml
v2/client.go
v2/client_test.go

... to table test.
Additionally, make travis run the tests :)

Add tests for GetCatalog and refactor

---

v2/bind.go
v2/client.go
v2/deprovision_instance.go
v2/errors.go
v2/get_catalog.go
v2/get_catalog_test.go
v2/poll_last_operation.go
v2/provision_instance.go
v2/unbind.go
v2/update_instance.go

Hone the formula for testing one of the interface methods

Improve error coverage in get_catalog_test.go

---

v2/client.go
v2/deprovision_instance.go
v2/deprovision_instance_test.go
v2/get_catalog_test.go
v2/provision_instance_test.go
v2/update_instance.go

...and begin testing the bodies of all requests

Add test for deprovision_instance.go

---

v2/bind.go
v2/bind_test.go

Add unit tests for bind.go

---

v2/deprovision_instance_test.go

Improve unit test coverage in deprovision_test.go

---

v2/deprovision_instance_test.go
v2/poll_last_operation.go
v2/poll_last_operation_test.go
v2/provision_instance_test.go
v2/unbind_test.go
v2/update_instance_test.go

Add test coverage for poll_last_operation.go

---

v2/bind_test.go
v2/client_test.go
v2/deprovision_instance_test.go
v2/get_catalog_test.go
v2/poll_last_operation_test.go
v2/provision_instance_test.go
v2/unbind_test.go
v2/update_instance_test.go

Refactor stuff since the transformations are obvious now that (mostly) everything is under test.

Refactor tests

---

v2/bind_test.go
v2/client_test.go
v2/deprovision_instance_test.go
v2/get_catalog_test.go
v2/poll_last_operation_test.go
v2/provision_instance.go
v2/provision_instance_test.go
v2/types.go
v2/unbind_test.go
v2/update_instance_test.go

As defined in https://github.com/openservicebrokerapi/servicebroker/issues/115

Add support for OSB alpha context profile

---

v2/get_catalog.go
v2/get_catalog_test.go
v2/types.go

Per https://github.com/openservicebrokerapi/servicebroker/pull/165

Add support for OSB parameter schemas

---

v2/errors.go
v2/errors_test.go

...to check for OSB-level errors.

Add IsHTTPError func

---

v2/fake/fake.go
v2/fake/fake_test.go

To check requests passed to the client

Add request capture to fake client

---

v2/fake/fake.go

for cases where you need to inject a specific fake client with a `v2.CreateFunc`

Add NewFakeClient method

---

v2/fake/fake.go

Found during kubernetes-incubator/service-catalog#954

Make fake client thread-safe

---

README.md

Update readme with current users

---

v2/client.go

Fix API header version

---

README.md

Since 2.12 is now supported :)

Update README with supported versions

---

v2/errors.go
v2/errors_test.go
v2/fake/fake.go
v2/fake/fake_test.go

Export wrapper errors for use in service catalog

---

v2/types.go

Fix minor typo: UnbindRequest -> BindRequest

---

v2/errors.go
v2/errors_test.go

Fixes a couple unsafe nil pointer dereferences in error handling functions.

Fix nil pointer panics in error functions

---

v2/errors.go
v2/errors_test.go

Makes IsHTTPError return status code as mentioned in #47.

Make IsHTTPError return HTTPStatusCodeError

---

docs/README.md

Small doc update

---

README.md

Add go report card results

---

docs/README.md

Going to try to do one of these per day until the docs are complete.

Make provision docs better

---

docs/README.md

Improve last operation docs

---

v2/auth_test.go
v2/bind.go
v2/bind_test.go
v2/client_test.go
v2/deprovision_instance.go
v2/deprovision_instance_test.go
v2/errors.go
v2/get_catalog_test.go
v2/poll_last_operation.go
v2/poll_last_operation_test.go
v2/provision_instance_test.go
v2/types.go
v2/unbind.go
v2/unbind_test.go
v2/update_instance.go
v2/update_instance_test.go

This fixes a bunch of minor things as reported from the "go report card".

Go report card fixes

---

docs/README.md

Add docs on DeprovisionInstance

---

v2/client.go
v2/errors.go
v2/fake/fake.go
v2/version.go
v2/version_test.go

https://goreportcard.com/report/github.com/onyiny-ang/go-open-service-broker-client

ammendments achieved A+ with 0 issues in go report card

---

v2/fake/fake_test.go
v2/interface_test.go
v2/poll_last_operation_test.go
v2/update_instance_test.go

Minimal coverage increase on poll_last_operation.go, interface.go, update_instance.go and fake.go

---

.travis.yml
v2/client_test.go

I haven't been able to confirm that it catches lint errors but I'm not sure if that's something I'm doing wrong in the testing or that the script is wrong.

gofmt in travis-ci

---

v2/client_test.go

Probably from one of my late-nite debugging sessions.

Remove dead code

---

v2/client.go
v2/client_test.go
v2/errors.go
v2/fake/fake.go
v2/fake/fake_test.go
v2/get_binding.go
v2/get_binding_test.go
v2/get_catalog_test.go
v2/interface.go
v2/types.go

As per the latest proposed GET spec change [here](https://github.com/mattmcneeney/servicebroker/blob/get-endpoints/spec.md#fetching-a-service-binding).

add alpha GET on bindings

---

v2/bind.go
v2/bind_test.go
v2/client.go
v2/errors.go
v2/errors_test.go
v2/fake/fake.go
v2/fake/fake_test.go
v2/get_binding_test.go
v2/get_catalog_test.go
v2/interface.go
v2/poll_binding_last_operation.go
v2/poll_binding_last_operation_test.go
v2/types.go
v2/unbind.go
v2/unbind_test.go

Adds support for asynchronous bind, unbind, and binding polling operations as alpha API methods.

add asynchronous binding operations

---

v2/fake/fake.go
v2/fake/fake_test.go

I would like to be able to codify what response the last action response should be from the fake based on the last operation the fake saw.

Adding a map for last action poll response.

---

v2/types.go
v2/update_instance.go
v2/update_instance_test.go

Add the Context field to UpdateInstanceRequest.

Add Context to UpdateInstanceRequest

---

v2/client.go
v2/client_test.go

Changes how failure responses are unmarshaled. Originally, if the response body contained either "error" or "description" keys but their values were not strings, we would get an unmarshaling error and would lose all conformant keys. Now, by unmarshaling into a `map[string]interface{}`, we can selectively keep the conformant keys.
This way, we now get the correct spec behavior where uninterpretable error message fields are simply ignored.

make HTTP errors more spec compliant

---

v2/types.go

This is a followup PR to #95, add period to comments.

Add period on PreviousValues comments

---

v2/client.go
v2/interface.go

Add plumbing to set Verbose flag in ClientConfiguration

---

v2/bind.go
v2/bind_test.go
v2/client.go
v2/constants.go
v2/deprovision_instance.go
v2/deprovision_instance_test.go
v2/provision_instance.go
v2/provision_instance_test.go
v2/unbind.go
v2/unbind_test.go
v2/update_instance.go
v2/update_instance_test.go

Export re-used constants

---

v2/deprovision_instance.go
v2/deprovision_instance_test.go
v2/poll_binding_last_operation.go
v2/poll_binding_last_operation_test.go
v2/poll_last_operation.go
v2/poll_last_operation_test.go
v2/unbind.go
v2/unbind_test.go

Since I managed to miss it in the last PR.

Replace internal constants with external ones

---

v2/get_catalog_test.go
v2/types.go

The current spec for this parameter is here: https://github.com/openservicebrokerapi/servicebroker/pull/334

Spec says bindings_retrievable

---

v2/constants.go

Add constants for known platforms

---

v2/types.go

Fixes #91 
Also for https://github.com/pmorie/osb-broker-lib/issues/22

Update json tag for OperationKey to conform to spec.

---

v2/client_test.go
v2/provision_instance.go
v2/provision_instance_test.go
v2/types.go

WIP, so far has raised a couple questions for https://github.com/openservicebrokerapi/servicebroker/pull/431

Add support for generic API extensions

---

v2/bind.go
v2/client.go
v2/deprovision_instance.go
v2/get_binding.go
v2/get_catalog.go
v2/poll_binding_last_operation.go
v2/poll_last_operation.go
v2/provision_instance.go
v2/unbind.go
v2/update_instance.go

cherry-pick #133 & #131  back to version 0.0.4.

cherry-pick close connections back to 0.0.4

---

v2/version.go

Add new method to get supported API versions

---

README.md
v2/bind.go
v2/bind_test.go
v2/client.go
v2/client_test.go
v2/errors.go
v2/get_binding.go
v2/get_binding_test.go
v2/get_instance.go
v2/get_instance_test.go
v2/interface.go
v2/poll_binding_last_operation.go
v2/poll_binding_last_operation_test.go
v2/types.go
v2/unbind.go
v2/unbind_test.go
v2/update_instance.go
v2/update_instance_test.go
v2/version.go
v2/version_test.go

Includes graduating all the previously alpha features.
closes #144

Add Version 2.14

---

go.mod
go.sum
v2/bind.go
v2/client.go
v2/generator/catalog.go
v2/generator/catalog_test.go
v2/generator/generator_test.go
v2/provision_instance.go
v2/unbind.go

Resolves #152, none of the klog methods that are in use currently have has breaking changes with the bumps to v1 or v2.

Bump klog to v2

---

auth_test.go
bind.go
client.go
client_test.go
deprovision_instance.go
fake/fake_test.go
generator/catalog_test.go
generator/generator.go
generator/generator_test.go
get_binding.go
get_catalog.go
get_instance.go
poll_binding_last_operation.go
poll_binding_last_operation_test.go
poll_last_operation.go
poll_last_operation_test.go
provision_instance.go
types.go
unbind.go
update_instance.go

Part of the 2.15 OSB API spec (#161)

Read the delay value from polling response

---

bind.go
bind_test.go
get_binding.go
get_binding_test.go
types.go

Endpoints in the binding response
