v2/bind.go, v2/client.go, v2/deprovision_instance.go, v2/get_catalog.go, v2/get_catalog_test.go, v2/poll_last_operation.go, v2/provision_instance.go, v2/provision_instance_test.go, v2/unbind.go, v2/update_instance.go
To make them pure unit tests, allow testing request parameters, delineate object for http checks and reactions, etc.
=> Refactor unit tests

v2/errors.go, v2/errors_test.go, v2/interface.go, v2/poll_last_operation.go
PollLastOperation may return an error for HTTP GONE responses from the broker, which is a valid response when checking the status of an async deprovision.
=> Add clarification about GONE responses for async deprovisions

v2/bind_test.go, v2/client.go, v2/client_test.go, v2/deprovision_instance_test.go, v2/get_catalog_test.go, v2/interface.go, v2/poll_last_operation_test.go, v2/provision_instance.go, v2/provision_instance_test.go, v2/types.go, v2/unbind_test.go, v2/update_instance_test.go, v2/version.go, v2/version_test.go
Adds support for version 2.12; removes alpha support for Context in earlier versions.  `LatestAPIVersion` now returns 2.12.
=> Semantic versioning; introduce v2.12

v2/bind.go, v2/bind_test.go, v2/client.go, v2/client_test.go, v2/deprovision_instance_test.go, v2/errors.go, v2/get_catalog.go, v2/get_catalog_test.go, v2/poll_last_operation.go, v2/poll_last_operation_test.go, v2/provision_instance.go, v2/provision_instance_test.go, v2/unbind.go, v2/unbind_test.go, v2/update_instance.go, v2/update_instance_test.go
The OSB spec states that platforms must differentiate between the HTTP status codes when a malformed response body is returned (see https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#orphans).  This change begins returning that data to the user, and fixes a couple cases that were not erroring when they should have with malformed response bodies.
=> Correctly model and handle malformed broker responses

v2/errors.go, v2/errors_test.go
I think printing the error strings when populated is what is desired here, but perhaps a better strategy could be utilized rather than this.
=> Make HTTPStatusCodeError error method print strings

v2/auth_test.go, v2/client.go, v2/interface.go
The change needed for implementing Bearer auth token support in Service Catalog ([#1044](https://github.com/kubernetes-incubator/service-catalog/pull/1044))
=> Bearer token auth support

v2/deprovision_instance.go, v2/deprovision_instance_test.go
Closes #51 
A Deprovision request should have the service ID and plan ID sent as query parameters rather than sent as part of the request body.
=> Fixes #51: Send service ID and plan ID as query parameters for deprovision

v2/client.go, v2/interface.go
Fixes #53. Cert data is passed to the client in ClientConfiguration.CAData.
=> Use supplied cert data for TLS authentication

v2/types.go
As per the spec: [Asynchronous Operations](https://github.com/openservicebrokerapi/servicebroker/blob/v2.12/spec.md#asynchronous-operations)
If a broker receives `accepts_incomplete` but doesn't need to fulfill a request asynchronously, it may choose to do so synchronously. However, if a broker does not receive `accepts_incomplete` but can only fulfill a request synchronously, THAT is the situation in which it will reject the request.
=> fix incorrect AcceptsIncomplete message

v2/deprovision_instance.go, v2/deprovision_instance_test.go, v2/provision_instance.go, v2/provision_instance_test.go, v2/update_instance.go, v2/update_instance_test.go
A `202 Accepted` response from the broker during a provision/deprovision without `accepts_incomplete` supplied should be treated as an error.
=> treat 202 as an error when async not supported

v2/client_test.go, v2/types.go
Remove the unused OriginatingIdentity field from the ProvisionResponse struct. The originating identity is not something sent in a response from a Broker.
Fixed a lint error.
=> Remove OriginatingIdentity from ProvisionResponse

README.md, v2/bind.go, v2/bind_test.go, v2/client.go, v2/client_test.go, v2/deprovision_instance_test.go, v2/get_catalog.go, v2/get_catalog_test.go, v2/poll_last_operation_test.go, v2/provision_instance_test.go, v2/types.go, v2/unbind_test.go, v2/update_instance_test.go, v2/version.go, v2/version_test.go
- Adds a version 2.13 API Version to the client
- Graduates OriginatingIdentity and ParameterSchemas from alpha and gates them on API Version >= 2.13
- Adds Context field to bind request
Closes: #81
=> update client for 2.13 

v2/fake/fake.go, v2/fake/fake_test.go
Replace the struct reactions with functions that yield the response and error components. This allows for the reactions to be more dynamic.
=> Use functions to generates responses to requests to the fake broker

v2/types.go, v2/update_instance.go, v2/update_instance_test.go
This PR is for #94 , intended to pass `previous_values` for updating instance as per the spec: https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#updating-a-service-instance
`ServiceID`, `OrgID`, `SpaceID` are deprecated, but `PlanID` is not. Leave all deprecated fields for now if there's no objection.
cc @frodenas
=> Add PreviousValues to UpdateInstanceRequest

v2/types.go, v2/update_instance.go, v2/update_instance_test.go
Validation through implementation of [OSB 437](https://github.com/openservicebrokerapi/servicebroker/pull/437).
This is to allow Dashboard URL to be returned in the response body to a PATCH /v2/service_instances/:service_id request.
=> Allow dashboard_url in response to update service instance

v2/bind.go, v2/client.go, v2/deprovision_instance.go, v2/get_binding.go, v2/get_catalog.go, v2/poll_binding_last_operation.go, v2/poll_last_operation.go, v2/provision_instance.go, v2/unbind.go, v2/update_instance.go
The Response Body should always be closed if there was no error executing the request.
See related issue https://github.com/kubernetes-incubator/service-catalog/issues/2276
=> Close the response Body

v2/client.go
fixes #132 
to test using k8s service catalog, do a `svcat sync broker ups-broker` repeatedly.  Without the fix, you see the number of established connections grow as reported by `sudo nsenter  -t $BROKERPID --net netstat -n -p`
With this fix, the number of established connections remains constant which is a small number related to the number of connections used within the last 90 seconds (IdleConnTimeout).
=> use defaults from DefaultTransport for our custom transport (ie timeouts)

v2/bind.go, v2/client.go, v2/generator/catalog.go, v2/generator/catalog_test.go, v2/generator/generator_test.go, v2/interface.go, v2/provision_instance.go, v2/unbind.go
I'm trying to migrate service catalog to kube 1.13 libraries. glog has been forked into [klog](https://github.com/kubernetes/klog) and everything has been migrated to it (see https://github.com/kubernetes/kubernetes/pull/70889). I'm just doing the same thing in this repo so that service catalog does not depend on glog anymore.
=> Migrate from glog to klog

v2/fake/fake.go, v2/fake/fake_test.go
- update test
@pmorie @duglin who has merge perms on this repo? 
for #121 to help enforce upstream usage in service-catalog.
Not required, but can be done piecemeal. Maybe good for new contributors?
=> enforce required fields on fake ProvisionRequest

v2/errors.go, v2/errors_test.go, v2/fake/fake.go, v2/fake/fake_test.go
This adds constants for ConcurrencyError, as documented in the [2.14 spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#error-codes)
I was going to change `AsyncErrorDescription` to not specifically mention service plans, but then I realized that `IsAsyncRequiredError` actually specifically checks the description (and not just the message) for equality; it seems possible that changing the description would break backwards compatibility.
(`ConcurrencyError` is useful when implementing asynchronous operations.)
=> v2/errors.go: Add constants for concurrency error

v2/get_catalog.go, v2/get_catalog_test.go, v2/types.go
This also removes all logic associated with RequestResponseSchema as this is not in any released (or pending release) version of the OSBAPI spec.
Resolves #147
=> Switch ServiceBindingSchema.Create to InputParametersSchema

README.md
Minor change in README, not strictly essential as the previous url redirects to the new one.
=> Update location of service-catalog repo in README

v2/provision_instance.go, v2/provision_instance_test.go, v2/types.go
This resolves #153. It might make sense to spin up another issue to implement https://github.com/openservicebrokerapi/servicebroker/pull/670 once it has been accepted.
=> Remove ExtensionAPIs from provision response

get_catalog.go, get_catalog_test.go, types.go, version.go, version_test.go
- plan_updateable
- maximum_polling_duration
- maintenance_info
Part of the 2.15 support #161
=> Added support for the following 2.15 Plan fields:

bind.go, bind_test.go
If there is a Route in the Bind Request then put it into the map instead of AppGUID again.
=> Fix: Route from BindRequest not passed on
